name: Repo sync GitHub -> Codeberg
on:
  push:
    branches:
    - '**'

jobs:
  codeberg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'https://codeberg.org/tobifroe/klog.git'
          GIT_USERNAME: tobifroe
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
